Display user surveys
EveningStarlight/SYSC_4806_Project pull request #35
Opened 2022-03-11 13:59 UTC by imran1503

Have the first test table being statically displayed. 
Next steps are: showing all relevant tables as well as the hyperlink to the entire table.

2022-03-11 15:52 UTC, EveningStarlight requested changes

2022-03-11 15:52 UTC, EveningStarlight commented on src/UserPage/SurveyerPage.js
> +// }
possibly remove commented code

2022-03-11 15:52 UTC, EveningStarlight commented on src/surveys.json
> +		"Q1Answers": []
resolve conflict with main

2022-03-20 03:16 UTC, imran1503 commented
Continued in a more modern branch

2022-03-20 03:16 UTC, closed without merging